export const services = [
  // HAIRCUTS
  {
    id: '1',
    name: "Ladies' Long Haircut",
    description: 'Precision cuts for long hair tailored to your face shape and lifestyle. Includes consultation, wash, cut, and styling.',
    price: 8000,
    duration: '60 min',
    icon: '✂️',
    category: 'hair',
    popular: true,
  },
  {
    id: '2',
    name: 'Bob & Pixie Cuts',
    description: 'Modern bob and pixie cuts for a fresh, stylish look.',
    price: 9500,
    duration: '45 min',
    icon: '✂️',
    category: 'hair',
  },
  {
    id: '3',
    name: "Ladies' Hair Trim",
    description: 'Quick trim to maintain your current style and keep ends healthy.',
    price: 3000,
    duration: '30 min',
    icon: '✂️',
    category: 'hair',
  },
  {
    id: '4',
    name: "Gents' Haircut (Master Stylist)",
    description: 'Expert haircut by Master Stylist Surith - precision cuts with premium service.',
    price: 2800,
    duration: '45 min',
    icon: '✂️',
    category: 'hair',
    popular: true,
  },
  {
    id: '5',
    name: "Gents' Haircut (Assistant)",
    description: 'Professional haircut by our trained assistants.',
    price: 1900,
    duration: '30 min',
    icon: '✂️',
    category: 'hair',
  },

  // BEARD SERVICES
  {
    id: '6',
    name: 'Beard Trimming',
    description: 'Expert beard shaping and trimming for a sharp, polished look.',
    price: 1000,
    duration: '20 min',
    icon: '🧔',
    category: 'beard',
  },
  {
    id: '7',
    name: 'Beard Shaving',
    description: 'Traditional wet shave with hot towel for a smooth finish.',
    price: 1200,
    duration: '30 min',
    icon: '🧔',
    category: 'beard',
  },
  {
    id: '8',
    name: 'Beard Color',
    description: 'Beard coloring to match or enhance your natural hair color.',
    price: 1000,
    duration: '25 min',
    icon: '🧔',
    category: 'beard',
  },

  // HAIR STYLING
  {
    id: '9',
    name: "Ladies' Hair Setting",
    description: 'Temporary hair settings and blowouts for any occasion.',
    price: 3500,
    duration: '45 min',
    icon: '💇‍♀️',
    category: 'styling',
  },
  {
    id: '10',
    name: "Gents' Hair Setting",
    description: 'Professional hair setting by our assistants.',
    price: 1500,
    duration: '30 min',
    icon: '💇‍♂️',
    category: 'styling',
  },

  // HAIR COLORING
  {
    id: '11',
    name: "Master Stylist Hair Coloring",
    description: 'Expert hair coloring by Master Stylist Surith - premium color services.',
    price: 30000,
    duration: '180 min',
    icon: '🎨',
    category: 'color',
    popular: true,
  },
  {
    id: '12',
    name: "Senior Assistant Hair Coloring",
    description: 'Professional hair coloring by our senior assistants.',
    price: 12000,
    duration: '120 min',
    icon: '🎨',
    category: 'color',
  },
  {
    id: '13',
    name: "Gents' Hair Coloring",
    description: 'Professional hair coloring services for men.',
    price: 5000,
    duration: '60 min',
    icon: '🎨',
    category: 'color',
  },
  {
    id: '14',
    name: "Ladies' Full Root Touch-Up",
    description: 'Complete root touch-up for color maintenance.',
    price: 7000,
    duration: '60 min',
    icon: '🖌️',
    category: 'color',
  },
  {
    id: '15',
    name: "Gents' Root Touch-Up",
    description: 'Root touch-up services for men.',
    price: 3500,
    duration: '30 min',
    icon: '🖌️',
    category: 'color',
  },
  {
    id: '16',
    name: "Ladies' Crown Root Touch-Up",
    description: 'Crown area root touch-up for targeted color maintenance.',
    price: 5000,
    duration: '45 min',
    icon: '🖌️',
    category: 'color',
  },
  {
    id: '17',
    name: "Ladies' Fringe Touch-Up",
    description: 'Fringe/bangs color touch-up.',
    price: 3000,
    duration: '20 min',
    icon: '🖌️',
    category: 'color',
  },
  {
    id: '18',
    name: 'Fashion Hair Color Lines',
    description: 'Trendy fashion color highlights and streaks.',
    price: 3000,
    duration: '60 min',
    icon: '🌈',
    category: 'color',
  },

  // HAIR REBOUNDING
  {
    id: '19',
    name: "Ladies' Hair Rebounding",
    description: 'Full hair rebonding for sleek, straight hair.',
    price: 14000,
    duration: '180 min',
    icon: '💆',
    category: 'treatment',
  },
  {
    id: '20',
    name: "Ladies' Crown Rebonding",
    description: 'Crown area rebonding for volume control.',
    price: 9500,
    duration: '120 min',
    icon: '💆',
    category: 'treatment',
  },
  {
    id: '21',
    name: "Ladies' Fringe Rebounding",
    description: 'Fringe rebonding for sleek bangs.',
    price: 8000,
    duration: '90 min',
    icon: '💆',
    category: 'treatment',
  },

  // HAIR STRAIGHTENING
  {
    id: '22',
    name: "Ladies' Hair Straightening",
    description: 'Full hair straightening treatment.',
    price: 12000,
    duration: '150 min',
    icon: '💆',
    category: 'treatment',
  },
  {
    id: '23',
    name: "Ladies' Crown Straightening",
    description: 'Crown area straightening for volume control.',
    price: 9000,
    duration: '100 min',
    icon: '💆',
    category: 'treatment',
  },
  {
    id: '24',
    name: "Ladies' Fringe Straightening",
    description: 'Fringe straightening for sleek bangs.',
    price: 7500,
    duration: '80 min',
    icon: '💆',
    category: 'treatment',
  },

  // HAIR RELAXING
  {
    id: '25',
    name: "Ladies' Hair Relaxing",
    description: 'Full hair relaxing treatment for smoother, manageable hair.',
    price: 10000,
    duration: '120 min',
    icon: '💆',
    category: 'treatment',
  },
  {
    id: '26',
    name: "Ladies' Crown Relaxing",
    description: 'Crown area relaxing for volume control.',
    price: 8000,
    duration: '90 min',
    icon: '💆',
    category: 'treatment',
  },
  {
    id: '27',
    name: 'Fringe Relaxing',
    description: 'Fringe relaxing treatment.',
    price: 7000,
    duration: '60 min',
    icon: '💆',
    category: 'treatment',
  },

  // HAIR PERMING
  {
    id: '28',
    name: "Gents' Hair Perming",
    description: 'Professional perming services for curls and waves.',
    price: 15000,
    duration: '120 min',
    icon: '🌀',
    category: 'treatment',
  },
]

export const team = [
  {
    id: '1',
    name: 'Alexandra Chen',
    role: 'Master Stylist',
    specialties: ['Balayage', 'Color Correction', 'Bridal Styling'],
    image: '/images/team/alexandra.webp',
    bio: 'With over 12 years of experience, Alexandra specializes in creative color techniques and has worked with fashion week stylists.',
    experience: 12,
    rating: 4.9,
    clients: 2500,
  },
  {
    id: '2',
    name: 'Marcus Williams',
    role: 'Senior Barber',
    specialties: ['Fade Cuts', 'Beard Design', 'Classic Styles'],
    image: '/images/team/marcus.webp',
    bio: 'Marcus brings precision and artistry to every cut. His attention to detail has made him a favorite among clients.',
    experience: 8,
    rating: 4.8,
    clients: 1800,
  },
  {
    id: '3',
    name: 'Sophie Laurent',
    role: 'Color Specialist',
    specialties: ['Highlights', 'Ombre', 'Fashion Colors'],
    image: '/images/team/sophie.webp',
    bio: 'Trained in Paris, Sophie creates stunning color transformations using the latest techniques and premium products.',
    experience: 10,
    rating: 4.9,
    clients: 2200,
  },
  {
    id: '4',
    name: 'David Park',
    role: 'Hair Stylist',
    specialties: ['Modern Cuts', 'Styling', 'Treatments'],
    image: '/images/team/david.avif',
    bio: 'David stays ahead of trends and specializes in contemporary cuts and styling for all hair types.',
    experience: 6,
    rating: 4.7,
    clients: 1200,
  },
]

export const portfolio = [
  {
    id: '1',
    before: '/images/portfolio/before-1.webp',
    after: '/images/portfolio/after-1.webp',
    category: 'Color',
    stylist: 'Sophie Laurent',
  },
  {
    id: '2',
    before: '/images/portfolio/before-2.webp',
    after: '/images/portfolio/after-2.webp',
    category: 'Cut',
    stylist: 'Alexandra Chen',
  },
  {
    id: '3',
    before: '/images/portfolio/before-3.webp',
    after: '/images/portfolio/after-3.webp',
    category: 'Treatment',
    stylist: 'David Park',
  },
  {
    id: '4',
    before: '/images/portfolio/before-4.webp',
    after: '/images/portfolio/after-4.webp',
    category: 'Color',
    stylist: 'Sophie Laurent',
  },
  {
    id: '5',
    before: '/images/portfolio/before-5.webp',
    after: '/images/portfolio/after-5.webp',
    category: 'Cut',
    stylist: 'Marcus Williams',
  },
  {
    id: '6',
    before: '/images/portfolio/before-1.webp',
    after: '/images/portfolio/after-6.webp',
    category: 'Styling',
    stylist: 'Alexandra Chen',
  },
  {
    id: '7',
    before: '/images/portfolio/before-2.webp',
    after: '/images/portfolio/after-7.webp',
    category: 'Color',
    stylist: 'Sophie Laurent',
  },
  {
    id: '8',
    before: '/images/portfolio/before-3.webp',
    after: '/images/portfolio/after-8.webp',
    category: 'Treatment',
    stylist: 'David Park',
  },
]

export const testimonials = [
  {
    id: '1',
    name: 'Jennifer Adams',
    service: 'Balayage & Cut',
    text: 'Absolutely incredible experience! Alexandra transformed my hair and I\'ve never felt more confident. The salon atmosphere is luxurious and relaxing.',
    rating: 5,
    date: '2024-01-10',
  },
  {
    id: '2',
    name: 'Robert Chen',
    service: 'Beard Grooming',
    text: 'Best haircut I\'ve ever had. Marcus pays attention to every detail and the hot towel finish is amazing. This is now my go-to spot.',
    rating: 5,
    date: '2024-01-08',
  },
  {
    id: '3',
    name: 'Maria Santos',
    service: 'Color Correction',
    text: 'Sophie saved my hair after a bad experience elsewhere. She\'s a true artist and professional. The results exceeded my expectations.',
    rating: 5,
    date: '2024-01-05',
  },
  {
    id: '4',
    name: 'Thomas Wright',
    service: 'Haircut & Style',
    text: 'The attention to detail here is unmatched. David really listened to what I wanted and delivered perfectly. Highly recommend!',
    rating: 5,
    date: '2024-01-03',
  },
  {
    id: '5',
    name: 'Emma Thompson',
    service: 'Bridal Styling',
    text: 'They made my wedding day perfect! The whole team was amazing and I felt like a princess. Cannot thank them enough!',
    rating: 5,
    date: '2024-01-01',
  },
  {
    id: '6',
    name: 'James Wilson',
    service: 'Full Service',
    text: 'From the moment you walk in, you feel like royalty. The service is top-notch and the results speak for themselves.',
    rating: 5,
    date: '2023-12-28',
  },
]

export const pricing = {
  men: [
    {
      id: '1',
      name: 'Essential',
      description: 'Perfect for regular maintenance',
      price: 4000,
      services: ['Haircut', 'Beard Trim', 'Hot Towel Finish'],
    },
    {
      id: '2',
      name: 'Premium',
      description: 'Our most popular package',
      price: 6500,
      services: ['Haircut', 'Beard Design', 'Scalp Massage', 'Hot Towel', 'Styling'],
      popular: true,
    },
    {
      id: '3',
      name: 'Executive',
      description: 'The full luxury experience',
      price: 10000,
      services: ['Haircut', 'Beard Sculpting', 'Facial', 'Scalp Treatment', 'Hot Towel', 'Styling'],
    },
  ],
  women: [
    {
      id: '1',
      name: 'Essential',
      description: 'Great for everyday style',
      price: 5500,
      services: ['Haircut', 'Wash & Style', 'Basic Treatment'],
    },
    {
      id: '2',
      name: 'Premium',
      description: 'Enhanced care and styling',
      price: 9500,
      services: ['Haircut', 'Deep Conditioning', 'Blow Dry', 'Style', 'Head Massage'],
      popular: true,
    },
    {
      id: '3',
      name: 'Luxury',
      description: 'Ultimate pampering session',
      price: 15000,
      services: ['Precision Cut', 'Hair Treatment', 'Scalp Massage', 'Blow Out', 'Style', 'Refreshments'],
    },
  ],
}

export const navigation = [
  { name: 'Services', href: '#services' },
  { name: 'Portfolio', href: '#portfolio' },
  { name: 'Team', href: '#team' },
  { name: 'Pricing', href: '#pricing' },
  { name: 'Testimonials', href: '#testimonials' },
  { name: 'Contact', href: '#contact' },
]

export const socialLinks = [
  { name: 'Instagram', href: 'https://instagram.com', icon: '📷' },
  { name: 'Facebook', href: 'https://facebook.com', icon: '👍' },
  { name: 'Twitter', href: 'https://twitter.com', icon: '🐦' },
]
